create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null,
  street_name text not null,
  area text not null,
  email text not null,
  grievance text not null,
  id_proof_path text not null,
  complaint_photo_paths text[] not null default '{}',
  created_at timestamptz not null default now()
);

create index if not exists complaints_created_at_idx
  on public.complaints (created_at desc);
